name: Selenium Automation

on:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Adjust the Python version as needed

      - name: Install Dependencies
        run: pip install -r requirements.txt
        working-directory: .github/workflows/requirements.txt  # Replace with the directory containing your requirements.txt

      - name: Run Selenium Script
        run: app.py  # Replace with your script's filename
        working-directory: your_working_directory  # Replace with your script's directory
