name: Selenium Automation

on:
  schedule:
    - cron: "*/3 * * * *"

jobs:
  selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Adjust the Python version as needed

      - name: Install Dependencies
        run: pip install -r requirements.txt
        working-directory: .  # Use . if requirements.txt is in the root directory

      - name: Run Selenium Script
        run: python app.py  # Replace with your script's filename
        working-directory: . # Replace with your script's directory
